### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by CoyAri** [CoyAri/Game_Collection#1]
Main
- [x] Styling
- [ ] Super Style (Something I really like)
- [ ] Links (Footer (maybe?))
- [x] Proper Icons/SVG

TicTacToe

- [x] Skeleton
- [x] Working?
- [ ] Styling

Match

- [x] Skeleton
- [x] Working?
- [ ] Hide effect on reset
- [x] Styling

Wordle/Guessing Word Game

- [ ] Skeleton
- [ ] Storage (API but for 5 letter words only (for now maybe?))
- [ ] Working?
- [ ] Styling

Typerace

- [ ] Skeleton
- [ ] Storage (API/to get words/sentences)
- [ ] Working?
- [ ] Styling

Multiplayer

- [ ] Research (Might not even do this tbh)

**Note: This can change with additions or subtractions of task to do**
